### ISSUE TITLE
Bug / Error / Issue

### ISSUE THREAD

**Issue by Primodial002** [ThinkByIt-Bot/FileStoreBot-Token#3]
![Screenshot (42)](https://github.com/ThinkByIt-Bot/FileStoreBot-Token/assets/115640591/adf2c2c2-0111-439f-83dc-4867788e15b2)
![Screenshot (43)](https://github.com/ThinkByIt-Bot/FileStoreBot-Token/assets/115640591/5170a848-67e3-4793-aa0e-840d48dbfa0f)

**Comment by thinkbyit** [comment]
watch the video carefully , https://youtu.be/ZxC_k4rJTiA

**Comment by Primodial002** [comment]
exactly followed your video , that error is coming after user solved shortener link and clicks /start command , it isnt send start welcome msg too and above error is coming in logs
